Repository spacetelescope/mosviz, pull requests merged in 2018-07, with the labels that each got.

#100 Add a mosviz command, and a startup action that automatically opens MOSViz viewer
  mosviz/__init__.py
  mosviz/cli.py
  mosviz/startup.py
  mosviz/viewers/mos_viewer.py
  setup.py
Labels: enhancement

#101 Use the public API to get categorical labels
  mosviz/data/ui/loader_selection.ui
  mosviz/loaders/loader_selection.py
  mosviz/viewers/mos_viewer.py
Labels: bug

#104 Include MOSViz in window title
  mosviz/startup.py
Labels: enhancement

#103 WIP: MOSViz GUI tests with pytest
  .gitignore
  .travis.yml
  appveyor.yml
  mosviz/conftest.py
  mosviz/loaders/deimos_loaders.py
  mosviz/tests/data/__init__.py
  mosviz/tests/data/cutouts/12004808.acs.v_6ac_.fits
  mosviz/tests/data/cutouts/12008179.acs.v_6ac_.fits
  mosviz/tests/data/cutouts/12012573.acs.v_6ac_.fits
  mosviz/tests/data/cutouts/12016058.acs.v_6ac_.fits
  mosviz/tests/data/cutouts/12020734.acs.v_6ac_.fits
  mosviz/tests/data/deimos_mosviz.tbl
  mosviz/tests/data/spec1D/spec1d.1153.151.12004808.fits
  mosviz/tests/data/spec1D/spec1d.1203.063.12008179.fits
  mosviz/tests/data/spec1D/spec1d.1205.091.12012573.fits
  mosviz/tests/data/spec1D/spec1d.1208.055.12016058.fits
  mosviz/tests/data/spec1D/spec1d.1209.080.12020734.fits
  mosviz/tests/data/spec2D/slit.1153.151R.fits.gz
  mosviz/tests/data/spec2D/slit.1203.063R.fits.gz
  mosviz/tests/data/spec2D/slit.1205.091R.fits.gz
  mosviz/tests/data/spec2D/slit.1208.055R.fits.gz
  mosviz/tests/data/spec2D/slit.1209.080R.fits.gz
  mosviz/tests/setup_package.py
  mosviz/viewers/mos_viewer.py
  mosviz/viewers/tests/test_mos_viewer.py
Labels: ready for review
